# Generated by Django 3.1.5 on 2021-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(default='/default-img.png', upload_to='documents/')),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('pengarang', models.CharField(blank=True, max_length=255)),
                ('penerbit', models.CharField(blank=True, max_length=255)),
                ('harga', models.PositiveIntegerField()),
                ('deskripsi', models.TextField(default='Beautiful masterpiece')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
