# Generated by Django 3.1.5 on 2021-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='alamat_pembeli',
            field=models.TextField(default='jl. mawar'),
        ),
    ]
