# Generated by Django 3.1.5 on 2021-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_pesanan_alamat_pembeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='bukti_tf',
            field=models.ImageField(default='/blm.png', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='konfirmasi',
            field=models.BooleanField(default=False),
        ),
    ]
