# Generated by Django 3.1.5 on 2021-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20210112_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='total_bayar',
            field=models.PositiveIntegerField(blank=True, default=100000),
            preserve_default=False,
        ),
    ]
