# Generated by Django 3.1.5 on 2021-01-12 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20210113_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='tgl_pesan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
