# Generated by Django 3.1.5 on 2021-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_pesanan_tgl_pesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='bukti_tf',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
