# Generated by Django 3.1.5 on 2021-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20210113_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='harga',
            field=models.BigIntegerField(),
        ),
    ]
